# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61524905d5342ef662556ec6d76469c6de09897f31a942f1734d15a66eb4eb39c7ff7ae67ba1aa35d5d82fa1dd056f5fcac9aaca777a554e9e38eabd95010161

test:
  secret_key_base: 19715840184d3acbe1148318901a16377ed8a35f2f01f96800aaed0842e63eafb777b7e5a0ff22c3039a2cd66bbf88cc38c1098542524b0141cb7affd415395e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
